import type { Branch } from "../types/Branch";

export const branches: Branch[] = [
  {
    id: 1,
    name: "Port Sudan Branch",
    liquidity: 45000000,
    availableAccounts: 3.0,
    filesReady: 24,
    status: "Ready",
    lastUpdated: "09:15",
    active: true,
  },
  {
    id: 2,
    name: "Shandi Branch",
    liquidity: 18000000,
    availableAccounts: 1.2,
    filesReady: 14,
    status: "Funding Soon",
    lastUpdated: "09:12",
    active: true,
  },
  {
    id: 3,
    name: "Dongola Branch",
    liquidity: 7000000,
    availableAccounts: 0.47,
    filesReady: 11,
    status: "Urgent Funding",
    lastUpdated: "09:09",
    active: true,
  },
  {
    id: 4,
    name: "Kassala Branch",
    liquidity: 36000000,
    availableAccounts: 2.4,
    filesReady: 19,
    status: "Ready",
    lastUpdated: "09:05",
    active: true,
  },
  {
    id: 5,
    name: "Atbara Branch",
    liquidity: 25000000,
    availableAccounts: 1.67,
    filesReady: 9,
    status: "Funding Soon",
    lastUpdated: "09:01",
    active: true,
  },
  {
    id: 6,
    name: "Alwady Branch",
    liquidity: 52000000,
    availableAccounts: 3.47,
    filesReady: 6,
    status: "Ready",
    lastUpdated: "08:58",
    active: true,
  },
  {
    id: 7,
    name: "Hasahessa Branch",
    liquidity: 12000000,
    availableAccounts: 0.8,
    filesReady: 16,
    status: "Urgent Funding",
    lastUpdated: "08:55",
    active: true,
  },
  {
    id: 8,
    name: "Gadaref Branch",
    liquidity: 30000000,
    availableAccounts: 2.0,
    filesReady: 13,
    status: "Funding Soon",
    lastUpdated: "08:52",
    active: true,
  },
  {
    id: 9,
    name: "Madani Branch",
    liquidity: 47000000,
    availableAccounts: 3.13,
    filesReady: 18,
    status: "Ready",
    lastUpdated: "08:48",
    active: true,
  },
  {
    id: 10,
    name: "Kosti Branch",
    liquidity: 9000000,
    availableAccounts: 0.6,
    filesReady: 8,
    status: "Urgent Funding",
    lastUpdated: "08:44",
    active: true,
  },
  {
    id: 11,
    name: "Obaied Branch",
    liquidity: 21000000,
    availableAccounts: 1.4,
    filesReady: 15,
    status: "Funding Soon",
    lastUpdated: "08:40",
    active: true,
  },
  {
    id: 12,
    name: "Sennar Branch",
    liquidity: 41000000,
    availableAccounts: 2.73,
    filesReady: 10,
    status: "Ready",
    lastUpdated: "08:35",
    active: true,
  },
];